### ISSUE TITLE
Docs: link not working anymore (README.md)

### ISSUE THREAD

**Issue by MathieuFrogames** [prime31/GoKit#56]
The following link http://prime31.com/unity/docs/#goKitDoc don't seems to work anymore.

**Comment by darthbator** [comment]
Sadly still not working

**Comment by mrcarriere** [comment]
Which one? Where?

- Michael

**Comment by darthbator** [comment]
This url [http://prime31.com/unity/docs/#goKitDoc](http://prime31.com/unity/docs/#goKitDoc) that says it has API docs listed in the readme. Now it just goes to the ios plugin docs
