### ISSUE TITLE
[Question] Player Camera on Path

### ISSUE THREAD

**Issue by darkevilmac** [prime31/GoKit#73]
Hi, I'm trying to create a simple system with a path that follows my player when they are moving. This leads me into my question, is there a method that would allow me to get the closest point on a path from a gameobject's transform.

Here you can see my totally professional explanation made with paint on what I'm trying to accomplish.

![2015-08-21_01-46-33](https://cloud.githubusercontent.com/assets/1813540/9404764/000f56ce-47a7-11e5-9919-2ab68cb70cf5.png)

The image is in 2D for obvious reasons but the same would apply in a 3d space.

**Comment by prime31** [comment]
GoKit is just a tweening library so there is nothing built into it to deal with anything other than the tween itself. You should be able to find a few different algorithms for closest point on a spline if you Google around for it.
