### ISSUE TITLE
Need help with playBackwards() 

### ISSUE THREAD

**Issue by jahongir9779** [prime31/GoKit#80]
I'm trying to play the tweenchain backwards but somehow it only plays forward but when i do playBackwards() it's doing nothing. 
One more thing, is it possible to remove a tween from chain after appending it ? thanks

**Comment by mrcarriere** [comment]
When you play backwards, it will reverse the playing direction and start
playing. If you are at the start of a tween, and you reverse it, you are at
the end of the tween already, so it would simply just "complete" the tween.

If you setup a TweenChain, and then you want to start playing it backwards,
you need to force the playhead to the "end" of the tween before you play it.

One way you could do that is by calling complete() then playBackwards() on
the tweenChain.

As it's designed, playBackwards() expects that you played an animation
forward for some amount of time before you request that it plays in reverse.

As for removing tweens from TweenChains, that's not currently possible.
Care to share your use case for that one?

**Comment by jahongir9779** [comment]
Thanks for the answer, 
I wanted to kinda simulate a time reverse effect by recording the positions in a list only the last 5 seconds of activity of a gameObject. So that's why i wanted to delete the oldest tween from the list and record new one if it already had recorded 5 seconds.

**Comment by mrcarriere** [comment]
Ah -- if I were you, I might save a list of tweens, and play them in a coroutine rather than constantly construct a tweenchain with the last five tweens -- or I might only construct the TweenChain once you're ready to playback.
