### ISSUE TITLE
How to check if Go has no animation running

### ISSUE THREAD

**Issue by jahongir9779** [prime31/GoKit#81]
I have a lot of objects and each running tweens, its a game like candy crush. The question is, is it possible to check if all tweens have completed without using each objects tween, like from "GoKit" instance in the scene or something?

**Comment by mrcarriere** [comment]
No, because you could set a tween to not destroy on complete and it would never report 0.

If you want to check if a set of tweens are done, consider constantly adding them to a tween flow and then you just need to check if the flow is complete.

- Michael

**Comment by jahongir9779** [comment]
thanx, i'll try tweenFlow
