### ISSUE TITLE
[FEATURE REQUEST] ECS Support

### ISSUE THREAD

**Issue by sathyaraj-shettigar** [prime31/GoKit#84]
Hi team,  
          Have you considered making a variant which supports ECS?

**Comment by mrcarriere** [comment]
I’d personally wait a bit until it sees more support within the engine. ECS is still in its early days at this point.

- Michael

**Comment by prime31** [comment]
Agreed. ECS isn’t even close to useable yet so there isn’t much point in trying to chase the API changes as they happen.
