### ISSUE TITLE
[Request] Tween value without using property

### ISSUE THREAD

**Issue by sathyarajshetigar** [prime31/GoKit#85]
Hi. Is it possible to tween a value without converting it to a property? 
say 0 to 1. LeanTween has a similar feature for most types. Here is an example

 LeanTween.value(gameObject, (float val) => {
                canvasGroup.alpha = val;
            }, 1, 0, tweenTime);

**Comment by prime31** [comment]
GoKit is pretty extensible so you can add in pretty much anything you want the fits into the idea of tweening or even just having a tick method called. For example, below is a quick and dirty implementation of an Action tween that can be called like this:

```csharp
Go.to( cube, 4, new GoTweenConfig() )
    .addTweenProperty( new ActionProperty( val => Debug.Log( val ) ) );
```

```csharp
public class ActionProperty : AbstractTweenProperty
{
	System.Action<float> _setter;
	
	float _startValue;
	float _endValue;


	public ActionProperty( System.Action<float> setter, float startValue = 0, float endValue = 1 )
	{
		_setter = setter;
		_startValue = startValue;
		_endValue = endValue;
	}


	public override void prepareForUse()
	{}


	public override void tick( float totalElapsedTime )
	{
		var easedValue = _easeFunction( totalElapsedTime, _startValue, _endValue, _ownerTween.duration );
		_setter( easedValue );
	}
}
```

**Comment by sathyarajshetigar** [comment]
Hi,
I tried using the code and it does not work as expected. Here is the code. All I get is the start value

public class GoFloatProperty : AbstractTweenProperty
{
    private Action<float> _setter;

    private float _startValue;
    private float _endValue;

    public GoFloatProperty(float startValue, float endValue, Action<float> setter)
    {
        _setter = setter;
        _startValue = startValue;
        _endValue = endValue;
    }

    public override void prepareForUse()
    {
    }

    public override void tick(float totalElapsedTime)
    {
        float easedValue = _easeFunction(totalElapsedTime, _startValue, _endValue, _ownerTween.duration);
        _setter(easedValue);

        UnityEngine.Debug.Log("Tick " + easedValue + " totalElapsedTime " + totalElapsedTime +
            " _ownerTween.duration " + _ownerTween.duration + " _startValue " + _startValue + " _endValue " + _endValue);
    }
}

//and used it like this
        Go.to(this, 1, new GoTweenConfig().addTweenProperty(new GoFloatProperty(100.0f, 0.0f, val => Debug.Log(val))));
//It prints only 100,100,100.........
Did I miss anything?

**Comment by sathyarajshetigar** [comment]
Awesome. That did work. Thanks a ton

**Comment by sathyarajshetigar** [comment]
Quick question. Does AbstractTweenProperty instance allocate memory?

**Comment by prime31** [comment]
@sathyarajshetigar there will a small allocation each time you call that method. If you are calling it every frame definitely cache the tween. If you are only calling it every so often no need to bother caching it.
