### ISSUE TITLE
Documentation installation (via github?)

### ISSUE THREAD

**Issue by tacman** [prime31/GoKit#91]
Since this isn't in the asset store, I'm trying to figure out the best way to install it, without simply cloning it and adding all the files to my project (though perhaps that's the best way?).

I haven't been successful going to the Package Manager and clicking on "Add from Git URL" and entering "https://github.com/prime31/GoKit.git"

What is the best way to install this plugin?

Thanks.

**Comment by prime31** [comment]
I just add it as a submodule and symlink from any folder in your project to Assets/Plugins/GoKit
